<a href="https://colab.research.google.com/github/jglim531/math-103.1-nlp/blob/main/03_Machine_Learning_Models_For_Text/Text_Classification_Dataset_Processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import Necessary Libraries

In [37]:
from datasets import load_dataset # Hugging Face dataset loader
import pandas as pd

### Load Dataset of Airline Sentiment

Link: https://huggingface.co/datasets/osanseviero/twitter-airline-sentiment

A sentiment analysis job about the problems of each major U.S. airline. Twitter data was scraped from February of 2015 and contributors were asked to first classify positive, negative, and neutral tweets, followed by categorizing negative reasons (such as "late flight" or "rude service").

Generally, the dataset contains whether the sentiment of the tweets was positive, neutral, or negative for six US airlines.

In [38]:
# How to load dataset from Hugging Face using the dataset title
airline_dataset = load_dataset("osanseviero/twitter-airline-sentiment")

In [39]:
# See the details of the dataset (this one only contains the train split, so will need to further split this data for train and test sets)
airline_dataset

DatasetDict({
    train: Dataset({
        features: ['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence', 'negativereason', 'negativereason_confidence', 'airline', 'airline_sentiment_gold', 'name', 'negativereason_gold', 'retweet_count', 'text', 'tweet_coord', 'tweet_created', 'tweet_location', 'user_timezone'],
        num_rows: 14640
    })
})

In [40]:
# Get the train dataset from the DatasetDict
airline_train = airline_dataset["train"]

# Convert it to .csv for a local copy
airline_train.to_csv("airline_sentiment.csv")

Creating CSV from Arrow format:   0%|          | 0/15 [00:00<?, ?ba/s]

3420804

In [41]:
# Convert to pandas directly after loading from Hugging Face
airline_dataset = airline_dataset["train"].to_pandas()

# Show the top N entries
airline_dataset.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,None,NaN,Virgin America,None,cairdin,None,0,@VirginAmerica What @dhepburn said.,None,2015-02-24 11:35:52 -0800,None,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,None,0.0000,Virgin America,None,jnardino,None,0,@VirginAmerica plus you've added commercials t...,None,2015-02-24 11:15:59 -0800,None,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,None,NaN,Virgin America,None,yvonnalynn,None,0,@VirginAmerica I didn't today... Must mean I n...,None,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,None,jnardino,None,0,@VirginAmerica it's really aggressive to blast...,None,2015-02-24 11:15:36 -0800,None,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,None,jnardino,None,0,@VirginAmerica and it's a really big bad thing...,None,2015-02-24 11:14:45 -0800,None,Pacific Time (US & Canada)

In [60]:
# Inspect entries of the train dataset
print("Airline Dataset (Train) - Two Examples per Label\n")

for sentiment in ["negative", "neutral", "positive"]:
    # Filter the subset to a specific sentiment then select two samples, random state makes it reproducible per run
    subset = airline_dataset[airline_dataset["airline_sentiment"] == sentiment].sample(2, random_state = 42)
    for _, row in subset.iterrows():
        print(f"Label: {row['airline_sentiment']}")
        print(f"Text:  {row['text']}\n")

Airline Dataset (Train) - Two Examples per Label

Label: negative
Text:  @united gate C 24 IAD. U released passengers to board w/others deplaning .50 peopleOn bridge while next flight  board http://t.co/HfoF33iyhi

Label: negative
Text:  @USAirways 1729 connecting in charlotte to houston. Mechanical issue determined while q'd to take off. And we checked our bags.

Label: neutral
Text:  @united we finally just arrive to Bogota, good but long flight!!

Label: neutral
Text:  @AmericanAir got a callback at 1 am, took care of it. thanks.

Label: positive
Text:  @SouthwestAir thanks for your excellent response time and assistance! All set :)

Label: positive
Text:  @JetBlue thanks. I appreciate your prompt response.

In [42]:
# Load from local copy
airline_test = pd.read_csv("/content/airline_sentiment.csv")

airline_test.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

### Load Data of Financial News Sentiment

Link: https://huggingface.co/datasets/zeroshot/twitter-financial-news-sentiment

The Twitter Financial News dataset is an English-language dataset containing an annotated corpus of finance-related tweets. This dataset is used to classify finance-related tweets for their sentiment.

Generally, the dataset contains whether the sentiment of the tweets (related to the stock market) was bearish, bullish, or neutral for six US airlines.

In [43]:
# Load data from Hugging Face
financial_dataset = load_dataset("zeroshot/twitter-financial-news-sentiment")

In [44]:
# Check downloaded datasets
financial_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 9543
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2388
    })
})

In [45]:
# The link to the dataset in Hugging Face defines the label as follows
id_to_label = {
    0: "Bearish",
    1: "Bullish",
    2: "Neutral"
}

In [46]:
# Add a new column called text_label to both train and validation datasets
financial_train = financial_dataset["train"].to_pandas() # Need to convert the Hugging Face dataset to pandas DataFrame first
financial_train["text_label"] = financial_train["label"].apply(lambda x: id_to_label[x])

financial_validation = financial_dataset["validation"].to_pandas() # Need to convert the Hugging Face dataset to pandas DataFrame first
financial_validation["text_label"] = financial_validation["label"].apply(lambda x: id_to_label[x])

In [53]:
# Convert it to .csv for a local copy
financial_train.to_csv("financial_sentiment_train.csv")
financial_validation.to_csv("financial_sentiment_validation.csv")

In [47]:
# Inspect entries of the train dataset
print("Financial Dataset (Train) - Two Examples per Label")
financial_train.groupby("label").head(2).sort_values("label")

Financial Dataset (Train) - Two Examples per Label

                                                  text  label text_label
0    $BYND - JPMorgan reels in expectations on Beyo...      0    Bearish
1    $CCL $RCL - Nomura points to bookings weakness...      0    Bearish
126           $ALTG: Dougherty & Company starts at Buy      1    Bullish
127  $AMD - AMD's Navi shows strong adoption - BofA...      1    Bullish
358  $LB - MKM Partners puts a number on Victoria's...      2    Neutral
359  $WING - Baird returns to Wingstop bull camp ht...      2    Neutral

In [57]:
print("Two Example Entries per Label of Financial Dataset (Train)\n")

for label_id in id_to_label:
    subset = financial_train[financial_train["label"] == label_id].sample(2, random_state = 42)
    for _, row in subset.iterrows():
        print(f"Label: {row['label']} ({row['text_label']})")
        print(f"Text:  {row['text']}\n")

Two Example Entries per Label of Financial Dataset (Train)

Label: 0 (Bearish)
Text:  Why These Top Oil Stocks All Tumbled More Than 10% in January

Label: 0 (Bearish)
Text:  Turkish lira weakens past key 6-per-dollar level

Label: 1 (Bullish)
Text:  $CHFS big buyers here. Might bounce before the close.

Label: 1 (Bullish)
Text:  $FIZZ - National Beverage +4% as analysts keep scrambling https://t.co/JoctxfxaLB

Label: 2 (Neutral)
Text:  (Free to read) Over 60% of Americans say that stock market performance has little or no impact on their personal fi… https://t.co/l3QZQ3KwJy

Label: 2 (Neutral)
Text:  Best Buy has dodged death, but for how long? Watch the full video here to see how Best Buy has survived the retail… https://t.co/fvVyAzsL94

In [49]:
# Inspect entries of the validation dataset
print("Financial Dataset (Validation) - Two Examples per Label")
financial_validation.groupby("label").head(2).sort_values("label")

Financial Dataset (Validation) - Two Examples per Label

                                                 text  label text_label
0   $ALLY - Ally Financial pulls outlook https://t...      0    Bearish
1   $DELL $HPE - Dell, HPE targets trimmed on comp...      0    Bearish
29  $ABEO as expected, keeps going higher. Cantor ...      1    Bullish
30  $CACI - CACI gains a bull on growth accelerati...      1    Bullish
92  AM Best Revises Outlooks to Stable for Sublimi...      2    Neutral
93  Analyst: Amazon Blocking FedEx Ground Good New...      2    Neutral

In [54]:
# Load from local copy
financial_test = pd.read_csv("/content/financial_sentiment_train.csv")

financial_test.head()

,Unnamed: 0,text,label,text_label
0,0,$BYND - JPMorgan reels in expectations on Beyo...,0,Bearish
1,1,$CCL $RCL - Nomura points to bookings weakness...,0,Bearish
2,2,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",0,Bearish
3,3,$ESS: BTIG Research cuts to Neutral https://t....,0,Bearish
4,4,$FNKO - Funko slides after Piper Jaffray PT cu...,0,Bearish

In [55]:
# Load from local copy
financial_validation = pd.read_csv("/content/financial_sentiment_validation.csv")

financial_validation.head()

,Unnamed: 0,text,label,text_label
0,0,$ALLY - Ally Financial pulls outlook https://t...,0,Bearish
1,1,"$DELL $HPE - Dell, HPE targets trimmed on comp...",0,Bearish
2,2,$PRTY - Moody's turns negative on Party City h...,0,Bearish
3,3,$SAN: Deutsche Bank cuts to Hold,0,Bearish
4,4,$SITC: Compass Point cuts to Sell,0,Bearish